-- 회원가입 DB 만들기

-- H2 DATABASE SQL

-- 테이블 삭제
DROP TABLE IF EXISTS member CASCADE;
-- 이 부분은 id 필드가 기본값으로 생성된 식별자로 사용될 것임을 나타냅니다.
-- 즉, 테이블에 새로운 레코드가 추가될 때마다, 이 id 필드는 자동으로 생성되고 이전 값보다 1 증가한 고유한 값이 할당됩니다.
-- 사용자가 id 값을 명시적으로 설정하지 않으면, 데이터베이스 시스템이 자동으로 이 값을 관리합니다.
-- 테이블 생성
CREATE TABLE member(

    generated by default as identity
    id bigint generated by default as identity,
    user_id varchar(255),
    user_pw varchar(255),
    user_name varchar(255),
    user_role varchar(255),
    joindate date default CURRENT_TIMESTAMP
)

-- row 추가
insert into member( id, user_id, user_pw, user_name, user_role, joindate )
      values ( 1, 'hong', '1234', '홍길동', 'ROLE_USER', '2022-09-09');
insert into member( id, user_id, user_pw, user_name, user_role, joindate )
      values ( 2, 'tom', '1234', '톰아저씨', 'ROLE_USER', '2022-09-09');
insert into member( id, user_id, user_pw, user_name, user_role, joindate )
      values ( 3, 'admin', '1234', '관리자', 'ROLE_ADMIN', '2022-09-09');
insert into member(,user_id, user_pw, user_name, user_role, joindate )
      values ('admin', '1234', '관리자', 'ROLE_ADmMIN', '2022-09-09');

-- 검색하기
SELECT * FORM member;

-- 커밋하기 : 실제 물리적으로 파일에 쓰기
commit;